### ISSUE TITLE
Errors while setting up nr-lambda

### ISSUE THREAD

**Issue by danielhartnell** [newrelic/nr-lambda-onboarding#1]
Hey there,

Thanks for the interesting tool. I was hoping to play around with this over the weekend but I ran into a few issues I was unable to address.

Based on your documented example args, I was able to get the CloudFormation stacks applied. I see the following behavior though:

```
❯ ./newrelic-cloud set-up-lambda-integration --nr-account-id blah --regions us-west-2 \
--linked-account-name "blah" \
--nr-api-key blah \
--nr-license-key blah
Created role [NewRelicLambdaIntegrationRole] with policy [None] in your default AWS account.


Failed actions:
  Function: None, Region: None, Error: Failed to set up lambda integration: 'NoneType' object is not subscriptable
```

Simply running it a second time immediately afterward, it works.

```
❯ ./newrelic-cloud set-up-lambda-integration --nr-account-id blah --regions us-west-2 \
--linked-account-name "blah" \
--nr-api-key blah \
--nr-license-key blah
Cloud integrations account [myaccount] already exists in New Relic account [blah].
The AWS Lambda integration is already enabled in Cloud integrations account [myaccount] of New Relic account [blah].
Setting up "newrelic-log-ingestion" function in regions: ['us-west-2']


Completed actions:
  Function: newrelic-log-ingestion, Region: us-west-2
```

It's unclear to me why it fails the first time. After the successful execution, I can load up the Lambda function in the AWS console and I receive the following error at the top of the page:

>An error occurred while listing cloudwatch-logs relations: 2 validation errors detected: Value '' at 'logGroupName' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'logGroupName' failed to satisfy constraint: Member must satisfy regular expression pattern: [\.\-_/#A-Za-z0-9]+ (Service: AWSLogs; Status Code: 400; Error Code: InvalidParameterException; Request ID: 84a2692d-7f2e-11e9-bd9f-f916ced906c2)

I have not had a chance to look into it more yet. It's unclear to me if that's preventing the integration from working. When I try to verify the AWS account connection (using the instructions from https://one.newrelic.com/launcher/infra-nerdlets.launcher-lambda-onboarding), it says that my linked account has failed to connect with New Relic.

Let me know if I can provide any extra info to help troubleshoot. For what it's worth, I have no other Lambda functions in the region I'm testing. I reviewed the CloudFormation stack application and there are no errors.

Cheers,
Daniel

**Comment by ardias** [comment]
Hi Daniel,
thanks for reporting the issue. We'll take a look and see if we can understand what's  happening.

The Lambda integration should be working, but only fetching data from CloudWatch. If you need more detailed metric information, you'll need to also execute the 2nd supported command `stream-lambda-logs`.

**Comment by danielhartnell** [comment]
Right on. Thanks @ardias. If I get a little time I can play around with it in my environment and see if I can get you anymore useful information. If you can't repro, let me know. Maybe it's something in scoped to my AWS account.

**Comment by ardias** [comment]
Hi @danielhartnell ,
I've commit a fix to a bug I saw related to naming issues of the AWS stack/role we create, so if you can, could you try it again?
It should should be "smart" enough to detect that you already have the Cloud integration account created and the lambda integration enabled, although it may create a new CloudFormation stack and a new AWS role because i changed the naming format of those.

**Comment by ardias** [comment]
And btw, regarding the error in the AWS console, that's "expected". We've contacted AWS and that's a bug in the console UI, so don't worry about it, everything should be working fine.

**Comment by danielhartnell** [comment]
Awesome. Thanks! It looks like things are working now. I'll go ahead and close this out. Cheers!
