### ISSUE TITLE
Problem running the script to setup lambda

### ISSUE THREAD

**Issue by Deadarius** [newrelic/nr-lambda-onboarding#2]
Hello!

#### Context:
- trying to follow the steps outlined in the documentation 
- aws cli is configured and works

#### Problem:
When running the script:
```
$ ./nr-lambda-onboarding-master/newrelic-cloud set-up-lambda-integration --nr-account-id "xxx" --linked-account-name "xxx" --nr-api-key "xxx" --nr-license-key "xxx" --regions "ap-southeast-2"
```
Getting the following output:
```
Failed actions:
  Function: None, Region: None, Error: Failed to set up lambda integration: HTTP Error 401: Unauthorized
```

**Comment by ardias** [comment]
Hi Alex,
this could be due to you not having permissions on the New Relic account to
enable Cloud integration. Please check in your account settings, which type
of user you are: owner, admin, user...
Other possibility may be the "nr-api-key" not having been created either
for you (api keys are per user) or for the account you're trying to use
(api keys are also created for a specific account).

**Comment by Deadarius** [comment]
Thank you for your response @ardias 

Turns out the problem was due to incorrect api key being used. Api keys generated on accounts page did not work at all. The only way I could generate the right api key is by going to https://api.newrelic.com/graphiql. Not sure if I am embarassing myself or it is somewhat confusing...

The issue is resolved either way.

**Comment by Deadarius** [comment]
In fact I actually still don't even understand how to manage graphql keys specifically

**Comment by ardias** [comment]
Hi Alex,
It's a bit unclear what the correct api key must be used. We've other
people be confused about the correct api key. We'll be updating the readme
to better explain which api must be used.
You should be able to see and create more api keys if you go to Account
Settings-> Users and Roles-> [select user] -> Api Keys.

I'm glad you managed you make it work after all.
